### ISSUE TITLE
Create a system class diagram

### ISSUE THREAD

**Issue by curlyLasagna** [Dami5021/Classroom_Tour#6]
# Guideline Instructions
- Identify objects
- What are the associations between them?
- What is their mulplicity?
- What are the attributes of the objects?
- What operations are defined on the objects?

## Buildings
Each building is an object
Each building has a room type
Each building contains many rooms
Each rooms contain the following:
- Seat count
- Components
- Wireless display capability
- Lecture capture capability
- Access control (How the room is accessed)

Create a system diagram using [MS Visio](https://tu-my.sharepoint.com/:u:/r/personal/lgascon1_students_towson_edu/_layouts/15/Doc.aspx?sourcedoc=%7Bd9d75011-dfd0-440d-a82e-fca60e38a7d9%7D&action=edit&or=PrevEdit)

### Example of system diagram
![](https://media.geeksforgeeks.org/wp-content/uploads/20200619000657/1111465.png)

**Comment by Webby234** [comment]
I made a few changes to the diagram. I'm sure we could add a few more methods to each class depending on how specific we want to get. We can talk about it tomorrow in class and finalize it

**Comment by curlyLasagna** [comment]
![Class_Diagram](https://github.com/Dami5021/Classroom_Tour/assets/44715649/dfe26677-64ac-4cdb-b870-b6c65a6ad6e8)

The class diagram that was submitted
