### ISSUE TITLE
Specify system database tables and primary & foreign key relationships

### ISSUE THREAD

**Issue by curlyLasagna** [Dami5021/Classroom_Tour#7]
The CSV files on discord should help you out.

**Comment by curlyLasagna** [comment]
I forgot to grab a screenshot of the database relations Friday last week. I'll grab it Monday

**Comment by curlyLasagna** [comment]
Imported csv files to Supabase. I'll set up relationships over the weekend

**Comment by curlyLasagna** [comment]
ER diagram I've come up with for database design

![Image](https://github.com/Dami5021/Classroom_Tour/assets/44715649/c2ac147e-44e4-410b-b5d6-ac6f77a8b7d0)

Not sure if this is what professor wanted us to make but this should explain enough

**Comment by Webby234** [comment]
Yeah that should work fine I was thinking we could have also just screenshotted the tables and explain them under it. But this probably explains it better anyway
